#!/bin/bash
#
# run as root from /etc/rc.local
#
PROGRAM=/home/pi/convert.py
#
# set to a file to debug what is happening
LOG="/tmp/alarm.log"
#LOG="/dev/null"
PIDCNVRT=/tmp/pidcnvrt.txt

if [ -e "${PIDCNVRT}" ]; then
  kill -SIGTERM  $(<"${PIDCNVRT}")
  rm ${PIDCNVRT}
  sleep 5
fi

nohup ${PROGRAM}  > ${LOG} 2>&1 &
echo $! > "${PIDCNVRT}"

# log message
psql -U alarm -c "insert into actions (action,cause) values ('restart listener','restart');"

echo "end"
