#!/bin/bash
#
# warn if the temperature is close to freezing or overheating
#
cd /home/pi

LO_TEMP=37
HI_TEMP=120;

IFS=$'\n'
query="select distinct on(name) name, round(temperature::numeric, 0)  from data where time = (select max(time) from temperature)  \
       and (name != 'outside' and  name not like 'hvac%') and (temperature < $LO_TEMP or temperature > $HI_TEMP)  group by name, time, temperature;"

result=`psql -F" " -t -A -U sensor -h pi -c "${query}"`
for line in ${result}; do
	./speak.sh "temperature warning  $line"
done;
